### ISSUE TITLE
copy resources and static files 

### ISSUE THREAD

**Issue by gherardovarando** [IPL-UV/IPL-UV.github.io#35]
isp.uv.es is now hosting  a lot of files (.pdf etc..) which should be moved in the `asset` folder

**Comment by JulioContrerasH** [comment]
Resolved. Files are in huggingface repository https://huggingface.co/datasets/isp-uv-es/Web_site_legacy

**Comment by JulioContrerasH** [comment]
Resolved. Files are in huggingface repository https://huggingface.co/datasets/isp-uv-es/Web_site_legacy
