### ISSUE TITLE
Bibtex rendering wrong for author field

### ISSUE THREAD

**Issue by gherardovarando** [IPL-UV/IPL-UV.github.io#60]
the author field is rendered wrongly, 

in particular the "and" is not treated as author separator. 

I think this should be solved by updating the bibtex_js to use v1.0.0 

e.g. 

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/pcooksey/bibtex-js@1.0.0/src/bibtex_js.min.js"></script>
```

**Comment by JulioContrerasH** [comment]
resolved

**Comment by JulioContrerasH** [comment]
resolved
