### ISSUE TITLE
add subpath variable to the hugo.toml

### ISSUE THREAD

**Issue by csaybar** [IPL-UV/IPL-UV.github.io#7]
Sorry, this will be painful to fix.

subdir="." # when deployed in root.
subdir="isp/" # when deployed in a repository

**Comment by gherardovarando** [comment]
this can be fixed by using Hugo functions and methods for resources 
check #8 (in particular the new layout for people in the new `isp_uv` theme)

**Comment by gherardovarando** [comment]
should we close this?

**Comment by csaybar** [comment]
yes! ty
